name: Lint and Format

on:
  push:
    branches:
      - '**'

jobs:
  run-linters:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run Black
        run: |
          black --line-length 100 --exclude '.venv/*' .

      - name: Run Flake8
        run: |
          flake8 . --exclude .venv --config .flake8

      - name: Run isort
        run: |
          isort . --skip .venv
